logo_title: GEEK BIN

style: black

favicon: /favicon.ico

menu:
  作品: /project
  域名: /domain
  友联: /links
  关于: /about
  Github: https://github.com/1x481n

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: false
  appId: 1gCp7tEcdUWN1auEs0thjFHB-gzGzoHsz
  appKey: Wn2nzII8c6pQiuP3G84XpT97

highlight:
  enable: true